### ISSUE TITLE
rclone: Configuration

### ISSUE THREAD

**Issue by mraht** [marklar423/KoboCloud-rclone#1]
Hi @marklar423, do you have any recommendation regarding the numerous configuration steps/questions for the setup of rclone? With the choices I set it didn't work :/.

**Comment by marklar423** [comment]
It varies based on which backend you're trying to connect to, but the rclone forum would probably be a better place to get more-informed help (I mostly just use it with Google drive).

You can also test `rclone sync` locally on your computer before putting the config file on the Kobo, and you should get an error message that explains what's wrong.

**Comment by mraht** [comment]
Ok, thanks!
